baseURL: https://aron.day
title: aron.day
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: /contact/
          weight: 30
        - name: Walt Disney World® Metrics
          url: /disney/
          weight: 15
        
params:
    author: Aron Day


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Aron Day
        description: |

          Howya, I'm Aron! </br>

          I'm a Solution Architect at Datadog, living in Dublin.

        imageUrl: "img/avatar.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/dayaron/"
        - name: github
          url: "https://github.com/aronday"
        - name: gitlab
          url: "https://gitlab.com/aronday"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/img/favicon.ico"
          favicon16x16: "/img/favicon-16x16.png"
          favicon32x32: "/img/favicon-32x32.png"
          apple_touch_icon: "/img/apple-touch-icon.png"
          safari_pinned_tab: "/img/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
